almacen/almacen/urls.py
from django.contrib import admin
from django.urls import path, include # agregamos el método include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls'))
]

almacen/productos/urls.py
# importar el método path
from django.urls import path
# importar las vistas
from .views import (
    # Producto
    ProductoListView,
    ProductoCreateView,
    # Categoria
    CategoriaListView,
    CategoriaCreateView,
    # Proveedor
    ProveedorListView,
    ProveedorCreateView
    
)

# nombre descriptivo para las url
app_name = "productos"

# crear el enrutamiento de las url
urlpatterns = [
    # producto
    path('', ProductoListView.as_view(), name="producto-list"),
    # nuevo producto
    path('nuevo', ProductoCreateView.as_view(), name="producto-create"),
    # categoria
    path('categorias/', CategoriaListView.as_view(), name="categoria-list"),
    path('categorias/nuevo', CategoriaCreateView.as_view(), name="categoria-create"),
    # proveedor
    path('proveedores/', ProveedorListView.as_view(), name="proveedor-list"),
    path('proveedores/nuevo', ProveedorCreateView.as_view(), name="proveedor-form"),
]

almacen/core/models.py
from django.db import models

# Create your models here.

almacen/productos/models.py
from django.db import models

# Create your models here.

# importar la clase Model de models.

# Sistema de Inventario Completo
class Categoria(models.Model):
    
    # crear los atributos
    nombre = models.CharField(max_length=100, unique=True)
    descripcion = models.TextField(null=True, blank=True)
    
    # ajustar la tabla
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ["nombre"]

    def __str__(self):
        return self.nombre  # Muestra el nombre de la categoría

class Proveedor(models.Model):
    
    # crear los atributos
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    direccion = models.TextField(null=True, blank=True)
    contacto = models.CharField(max_length=100, null=True, blank=True)
    
    # ajustar la tabla
    class Meta:
        verbose_name = "Proveedor"
        verbose_name_plural = "Proveedores"
        ordering = ["nombre"]
    
    def __str__(self):
        return self.nombre  # Muestra el nombre del proveedor
    
# create table Producto()
class Producto(models.Model): # aplicando herencia

    # crear los atributos
    nombre = models.CharField(max_length=50) # nombre varchar(50) not null
    descripcion = models.TextField(null=True, max_length=150) # descripcion varchar(150)
    precio_compra = models.DecimalField(max_digits=12, decimal_places=2) # precio decimal(12,2) not null
    precio_venta = models.DecimalField(max_digits=12, decimal_places=2) # precio decimal(12,2) not null
    activo = models.BooleanField(default=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    # ajustar la tabla
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        ordering = ["nombre"]


    # crear un metodo
    def __str__(self): # polimorfismo
        return f"{self.nombre} - {self.stock} unidades"

almacen/productos/forms.py
from django import forms
from .models import Categoria, Proveedor, Producto

# crear un formulario personalizado para las Categorias
class CategoriaForm(forms.ModelForm):
    # ajuste al formulario generico
    class Meta:
        model = Categoria
        fields = ["nombre", "descripcion"]
        widgets = {
            "nombre": forms.TextInput(attrs={ "class": "form-control", "placeholder": "Nombre de la Categoria"}),
            "descripcion": forms.Textarea(attrs={ "class": "form-control", "placeholder": "Descripción de la Categoria", "rows": 3 })
        }
        
# crear un formulario personalizado para los proveedores
class ProveedorForm(forms.ModelForm):
    # ajustes al formulario
    class Meta:
        model = Proveedor
        fields = ["nombre", "telefono", "email", "direccion", "contacto"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Proveedor"}),
            "telefono": forms.TextInput(attrs={"class": "form-control", "placeholder": "70544596", "type": "cel"}),
            "email": forms.TextInput(attrs={"class": "form-control", "placeholder": "alguien@example.com", "type": "email"}),
            "direccion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Direccion del proveedor", "rows": 3 }),
            "contacto": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Contacto"}),
        }

# crear un formulario personalizado para los productos
class ProductoForm(forms.ModelForm):
    # ajustes al formulario
    class Meta:
        model = Producto
        fields = ["nombre", "descripcion", "precio_compra", "precio_venta", "activo", "categoria", "proveedor"]
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control", "placeholder": "Nombre del Producto"}),
            "descripcion": forms.Textarea(attrs={"class": "form-control", "placeholder": "Descripcion del Producto", "rows": 3}),
            "precio_compra": forms.NumberInput(attrs={"class": "form-control", "placeholder": "0.00", "step": "0.01"}),
            "precio_venta": forms.NumberInput(attrs={"class": "form-control", "placeholder": "0.00", "step": "0.01"}),
            "activo": forms.CheckboxInput(attrs={"class": "form-check-input"}),
            "categoria": forms.Select(attrs={"class": "form-select"}),
            "proveedor": forms.Select(attrs={"class": "form-select"}),
        }

almacen/core/views.py
from django.shortcuts import render

# Create your views here.

almacen/productos/views.py
from django.shortcuts import render
# importar vistas genericas
from django.views.generic import ListView, CreateView
# importar las clases
from .models import Producto, Categoria, Proveedor
# importar método reverse_lazy
from django.urls import reverse_lazy
# importar los formularios personalizados
from .forms import CategoriaForm, ProveedorForm, ProductoForm

# Create your views here.

# crear una clase generica para mostrar el listado de productos
class ProductoListView(ListView):
    
    # Indicar el modelo base
    model = Producto
    # Indicamos el template (plantilla)
    template_name = "producto/producto-list.html"
    # nombre del contexto del objetos
    context_object_name = "productos"

# crear una clase generica para guardar un nuevo producto
class ProductoCreateView(CreateView):
    
    model = Producto
    form_class = ProductoForm
    template_name = "producto/producto-form.html"
    success_url = reverse_lazy("productos:producto-list")
    
    
# crear una clase generica para mostrar el listado de categorias
class CategoriaListView(ListView):
    
    model = Categoria
    template_name = "categoria/categoria-list.html"
    context_object_name = "categorias"

# crear una clase generica para guardar una nueva categoria
class CategoriaCreateView(CreateView):
    
    model = Categoria
    form_class = CategoriaForm
    template_name = "categoria/categoria-form.html"
    success_url = reverse_lazy("productos:categoria-list")
    
    
# crear una clase generica para mostrar el listado de proveedor
class ProveedorListView(ListView):
    
    model = Proveedor
    template_name = "proveedor/proveedor-list.html"
    context_object_name = "proveedores"

# crear una clase generica para guardar un nuevo proveedor
class ProveedorCreateView(CreateView):
    
    model = Proveedor
    form_class = ProveedorForm
    template_name = "proveedor/proveedor-form.html"
    success_url = reverse_lazy("productos:proveedor-list")

almacen/core/templates/core/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} Mi Proyecto {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">🏪 Almacen</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'productos:categoria-list' %}">Categorias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'productos:proveedor-list' %}">Proveedores</a>
                        </li>       
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'productos:producto-list' %}">Productos</a>
                        </li>                     
                    </ul>
                    <!-- <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form> -->
                </div>
            </div>
        </nav>
    </header>

    <main>
        <!-- Contenido dinámico -->
         <div class="container">
            {% block content %}
            {% endblock %}
         </div>        
    </main>

    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
</body>

</html>

almacen/productos/templates/categoria/categoria-form.html
{% extends "core/base.html" %}

{% block title %} Nueva Categoria {% endblock %}


{% block content %}
<form method="post">
     {% csrf_token %}
    <div class="card mt-4 shadown-lg">
        <div class="card-header">
            <h3 class="card-title">Nueva Categoria</h3>
        </div>
        <div class="card-body">           
            {{ form.as_table }}
        </div>
        <div class="card-footer d-flex justify-content-between">
            <button class="btn btn-success" type="submit">✅ Guardar</button>
            <a href="{% url 'productos:categoria-list' %}" class="btn btn-outline-info">Cancelar</a>    
        </div>
    </div>
    

    
</form>
{% endblock %}

almacen/productos/templates/categoria/categoria-list.html
{% extends "core/base.html" %}

{% block title %} Listado de Categorias {% endblock %}

{% block content %}
<h1 class="text-center">Listado de Categorias</h1>
<a href="{% url 'productos:categoria-create' %}" class="btn btn-outline-success">Nueva Categoria</a>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
    </tr>
  </thead>
  <tbody>
    {% for c in categorias %}
    <tr>
      {% comment %} agregar un enumerate {% endcomment %}
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ c.nombre }}</td>
      <td>{{ c.descripcion }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

almacen/productos/templates/producto/producto-form.html
{% extends "core/base.html" %}

{% block title %} Nuevo Producto {% endblock %}


{% block content %}
<form method="post">
     {% csrf_token %}
    <div class="card mt-4 shadown-lg">
        <div class="card-header">
            <h3 class="card-title">Nuevo Producto</h3>
        </div>
        <div class="card-body">           
            {{ form.as_table }}
        </div>
        <div class="card-footer d-flex justify-content-between">
            <button class="btn btn-success" type="submit">✅ Guardar</button>
            <a href="{% url 'productos:producto-list' %}" class="btn btn-outline-info">Cancelar</a> 
        </div>
    </div>
{% endblock %}

almacen/productos/templates/producto/producto-list.html
{% extends "core/base.html" %}
{% block title %} Listado de Productos {% endblock %}

{% block content %}
<h1 class="text-center">Listado de Productos</h1>
<a href="{% url 'productos:producto-create' %}" class="btn btn-outline-success">Nuevo Producto</a>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Codigo</th>
      <th scope="col">Nombre</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Precio Venta</th>
    </tr>
  </thead>
  <tbody>
    {% comment %} Iterar sobre los productos de la BD {% endcomment %}
    {% for p in productos %}
    <tr>
      {% comment %} agregar un enumerate {% endcomment %}
      <th scope="row">{{ forLoop.counter }}</th> 
      <th>{{ p.id }}</th>
      <td>{{ p.nombre }}</td>
      <td>{{ p.descripcion }}</td>
      <td>@{{ p.precio_venta }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

almacen/productos/templates/proveedor/proveedor-form.html
{% extends "core/base.html" %}

{% block titulo %}Nuevo Proveedor{% endblock %}

{% block content %}
<form method="post">
     {% csrf_token %}
    <div class="card mt-4 shadown-lg">
        <div class="card-header">
            <h3 class="card-title">Nuevo Proveedor</h3>
        </div>
        <div class="card-body">           
            {{ form.as_table }}
        </div>
        <div class="card-footer d-flex justify-content-between">
            <button class="btn btn-success" type="submit">✅ Guardar</button>
            <a href="{% url 'productos:proveedor-list' %}" class="btn btn-outline-info">Cancelar</a>    
        </div>
    </div>
    
</form>
{% endblock %}

almacen/productos/templates/proveedor/proveedor-list.html
{% extends "core/base.html" %}

{% block titulo %}Lista de Proveedor{% endblock %}

{% block content %}
<h1 class="text-center">Listado de Proveedores</h1>
<a href="{% url 'productos:proveedor-form' %}" class="btn btn-outline-success">Nuevo Proveedor</a>
<hr>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nombre</th>
      <th scope="col">Telefono</th>
      <th scope="col">Contacto</th>
    </tr>
  </thead>
  <tbody>
    {% for p in proveedores %}
    <tr>
      {% comment %} agregar un enumerate {% endcomment %}
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ p.nombre }}</td>
      <td>{{ p.telefono }}</td>
      <td>{{ p.contacto }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}